### ISSUE TITLE
关于基本参数的问题

### ISSUE THREAD

**Issue by fjhfjhfjhfjy** [Waheal/MGSL#2]
基本参数只有一个AggressiveOpts
已知问题：
使用java13及以上版本在开服参数中加入AggressiveOpts，VM将不会启动。
原因：java11弃用了该参数，java12移除了该参数
解决方案：删除该参数
（某些新手因为看到开服器后面要4G内存的参数就选了第一个优化参数，就会出现使用高版本服务端开不起来的问题）

**Comment by Waheal** [comment]
已添加部分提示
